import {before,after,test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {Kysely,PGliteDialect,PostgresDialect} from 'kysely';import {PGlite} from '@electric-sql/pglite';import {Pool} from 'pg';
import {migrate} from '../src/server/db/migrate.ts';import {BookingService} from '../src/server/booking/service.ts';
const db=new Kysely({dialect:process.env.TEST_DATABASE_URL?new PostgresDialect({pool:new Pool({connectionString:process.env.TEST_DATABASE_URL,max:5})}):new PGliteDialect({pglite:new PGlite()})});
before(()=>migrate(db,new URL('../migrations',import.meta.url).pathname));after(()=>db.destroy());
async function fixture(){const uid=randomUUID();await db.insertInto('user').values({id:uid,name:'Admin',email:uid+'@test.invalid',emailVerified:false,username:'u'+uid}).execute();const b=await db.insertInto('business').values({id:randomUUID(),name:'Booking business',timezone:'Europe/Kaliningrad'}).returningAll().executeTakeFirstOrThrow();await db.insertInto('business_member').values({business_id:b.id,user_id:uid,role:'owner',status:'active'}).execute();const svc=new BookingService(db);const service=await svc.configure(uid,b.public_id,{kind:'service',name:'Консультация',duration_minutes:60,buffer_before_minutes:15,buffer_after_minutes:15});const resource=await svc.configure(uid,b.public_id,{kind:'specialist',name:'Александр'});await svc.configure(uid,b.public_id,{kind:'links',specialist_id:resource.id,service_ids:[service.id]});for(let weekday=0;weekday<7;weekday++)await svc.configure(uid,b.public_id,{kind:'schedule',specialist_id:resource.id,weekday,intervals:[{start:540,end:1080}]});const date=new Date(Date.now()+3*86400000).toISOString().slice(0,10);const slots=await svc.slots(uid,b.public_id,service.id,resource.id,date);return {uid,b,svc,service,resource,date,slots,body:{service_id:service.id,specialist_id:resource.id,starts_at:slots[0],client:{name:'Иван'},request_key:randomUUID()}};}
test('booking uses shared client, protects overlapping slots, schedules reminders and deduplicates replay',async()=>{const f=await fixture();const booking=await f.svc.create(f.uid,f.b.public_id,f.body);assert.equal(booking.status,'confirmed');const replay=await f.svc.create(f.uid,f.b.public_id,f.body);assert.equal(replay.id,booking.id);assert.equal((await db.selectFrom('client').selectAll().where('business_id','=',f.b.id).execute()).length,1);await assert.rejects(f.svc.create(f.uid,f.b.public_id,{...f.body,request_key:randomUUID(),starts_at:f.slots[1]}),e=>e.code==='BOOKING_SLOT_UNAVAILABLE');assert.equal((await db.selectFrom('booking_reminder').selectAll().where('booking_id','=',booking.id).execute()).length,3);});
test('failed reschedule preserves old reservation; cancellation frees it and retains history',async()=>{const f=await fixture();const a=await f.svc.create(f.uid,f.b.public_id,f.body);const b=await f.svc.create(f.uid,f.b.public_id,{...f.body,request_key:randomUUID(),starts_at:f.slots.at(-1)});await assert.rejects(f.svc.change(f.uid,f.b.public_id,a.id,{action:'reschedule',revision:1,starts_at:b.starts_at.toISOString()}),e=>e.code==='BOOKING_SLOT_UNAVAILABLE');assert.equal((await db.selectFrom('booking').select('starts_at').where('id','=',a.id).executeTakeFirstOrThrow()).starts_at.toISOString(),a.starts_at.toISOString());await f.svc.change(f.uid,f.b.public_id,a.id,{action:'cancel',revision:1});assert.ok((await f.svc.slots(f.uid,f.b.public_id,f.service.id,f.resource.id,f.date)).includes(a.starts_at.toISOString()));assert.equal((await db.selectFrom('booking_history').selectAll().where('booking_id','=',a.id).execute()).length,2);assert.ok((await db.selectFrom('booking_reminder').selectAll().where('booking_id','=',a.id).execute()).every(r=>r.status==='cancelled'));});
test('date exception overrides weekly hours and access is business scoped',async()=>{const f=await fixture();await f.svc.configure(f.uid,f.b.public_id,{kind:'exception',specialist_id:f.resource.id,date:f.date,intervals:[],reason:'Отпуск'});assert.deepEqual(await f.svc.slots(f.uid,f.b.public_id,f.service.id,f.resource.id,f.date),[]);await assert.rejects(f.svc.create(f.uid,f.b.public_id,f.body),e=>e.code==='BOOKING_SLOT_UNAVAILABLE');await assert.rejects(f.svc.catalog(randomUUID(),f.b.public_id),e=>e.code==='BUSINESS_NOT_FOUND');});
test('two simultaneous requests cannot reserve the same specialist slot',{skip:!process.env.TEST_DATABASE_URL&&'Requires PostgreSQL connections'},async()=>{const f=await fixture();const results=await Promise.allSettled([f.svc.create(f.uid,f.b.public_id,f.body),f.svc.create(f.uid,f.b.public_id,{...f.body,request_key:randomUUID()})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.code,'BOOKING_SLOT_UNAVAILABLE');});
test('Telegram booking menu creates linked booking and queues only current reminder once',async()=>{
 const {routeBot}=await import('../src/server/bot/router.ts');const {queueBookingReminder}=await import('../src/server/booking/worker.ts');const f=await fixture();const connection=randomUUID();await db.insertInto('business_connection').values({id:connection,business_id:f.b.id,platform:'telegram',status:'connected',external_account_id:randomUUID(),display_name:'test'}).execute();await db.insertInto('telegram_runtime').values({connection_id:connection,generation:randomUUID(),status:'ready'}).execute();await db.insertInto('business_solution').values({business_id:f.b.id,solution_code:'booking',status:'active',starts_at:new Date(),expires_at:null}).execute();let event=1;
 const send=text=>db.transaction().execute(tx=>routeBot(tx,{businessId:f.b.id,connectionId:connection,platform:'telegram',userId:'999',eventId:String(event++),text}));const choice=async()=>JSON.parse((await db.selectFrom('telegram_dialog').select('fields').where('connection_id','=',connection).executeTakeFirstOrThrow()).fields)[0].label;
 await send('/start');await send('Онлайн-запись');await send(await choice());await send(await choice());await send(f.date);await send(await choice());await send('Анна');await send('Подтвердить');const booking=await db.selectFrom('booking').selectAll().where('business_id','=',f.b.id).executeTakeFirstOrThrow();assert.equal(booking.source,'telegram');assert.equal((await db.selectFrom('telegram_dialog').select('mode').where('connection_id','=',connection).executeTakeFirstOrThrow()).mode,'menu');
 await db.updateTable('booking_reminder').set({due_at:new Date(0)}).where('booking_id','=',booking.id).where('kind','=','24h').execute();await queueBookingReminder(db);await queueBookingReminder(db);const queued=await db.selectFrom('telegram_outbox').selectAll().where('connection_id','=',connection).where('booking_reminder_id','is not',null).execute();assert.equal(queued.length,1);
});
