import {randomUUID} from 'node:crypto';import type {Kysely} from 'kysely';import type {Database} from '../db/schema.ts';import {nextOccurrence,type Recurrence} from './recurrence.ts';import {postDeliveryResult} from './delivery.ts';
export async function queueScheduledPost(db:Kysely<Database>){
 const candidate=await db.selectFrom('post as p').innerJoin('business_solution as s','s.business_id','p.business_id').select(['p.id','p.business_id']).where('s.solution_code','=','autopost').where('s.status','in',['active','trial']).where('p.status','=','scheduled').where('p.scheduled_at','<=',new Date()).orderBy('p.scheduled_at').executeTakeFirst();if(!candidate)return false;
 return db.transaction().execute(async tx=>{await tx.selectFrom('business').select('id').where('id','=',candidate.business_id).forUpdate().execute();const post=await tx.selectFrom('post').selectAll().where('id','=',candidate.id).where('status','=','scheduled').forUpdate().executeTakeFirst();if(!post)return false;await tx.updateTable('post').set({status:'publishing',updated_at:new Date()}).where('id','=',post.id).execute();const deliveries=await tx.selectFrom('post_delivery as d').innerJoin('post_target as t','t.id','d.target_id').innerJoin('business_connection as c','c.id','t.connection_id').select(['d.id','t.connection_id','t.external_id','t.platform','t.active','c.status as connection_status']).where('d.post_id','=',post.id).where('d.status','=','pending').execute();
  for(const d of deliveries){if(!d.active||d.connection_status!=='connected'){await postDeliveryResult(tx,d.id,'failed',null,'TARGET_UNAVAILABLE');continue;}const buttons=post.buttons as {text:string;url:string}[];const row={connection_id:d.connection_id,post_delivery_id:d.id,message:post.text,delivered_at:null,last_error:null};if(d.platform==='telegram')await tx.insertInto('telegram_outbox').values({...row,chat_id:d.external_id,api_payload:JSON.stringify(buttons.length?{reply_markup:{inline_keyboard:buttons.map(b=>[{text:b.text,url:b.url}])}}:{})}).onConflict(oc=>oc.column('post_delivery_id').doNothing()).execute();else await tx.insertInto('vk_outbox').values({...row,peer_id:d.external_id,api_payload:JSON.stringify({owner_id:d.external_id,from_group:1,guid:d.id,message:post.text+(buttons.length?'\n\n'+buttons.map(b=>b.text+': '+b.url).join('\n'):'')})}).onConflict(oc=>oc.column('post_delivery_id').doNothing()).execute();await tx.updateTable('post_delivery').set({status:'publishing'}).where('id','=',d.id).execute();}return true;
 });
}
export async function materializeRecurringPost(db:Kysely<Database>){
 const candidate=await db.selectFrom('post_schedule as p').innerJoin('business_solution as s','s.business_id','p.business_id').select(['p.post_id','p.business_id']).where('s.solution_code','=','autopost').where('s.status','in',['active','trial']).where('p.active','=',true).where('p.next_at','<=',new Date()).orderBy('p.next_at').executeTakeFirst();if(!candidate)return false;
 return db.transaction().execute(async tx=>{await tx.selectFrom('business').select('id').where('id','=',candidate.business_id).forUpdate().execute();const schedule=await tx.selectFrom('post_schedule').selectAll().where('post_id','=',candidate.post_id).where('active','=',true).where('next_at','<=',new Date()).forUpdate().executeTakeFirst();if(!schedule?.next_at)return false;const template=await tx.selectFrom('post').selectAll().where('id','=',schedule.post_id).executeTakeFirstOrThrow();const post=await tx.insertInto('post').values({id:randomUUID(),business_id:template.business_id,text:template.text,buttons:template.buttons,status:'scheduled',scheduled_at:schedule.next_at,created_by:template.created_by,request_key:'occurrence:'+schedule.post_id+':'+schedule.next_at.toISOString(),request_hash:template.request_hash,template_id:template.id,occurrence_at:schedule.next_at}).onConflict(oc=>oc.columns(['template_id','occurrence_at']).doNothing()).returning('id').executeTakeFirst();if(post){const targets=await tx.selectFrom('post_delivery').select('target_id').where('post_id','=',template.id).execute();for(const t of targets)await tx.insertInto('post_delivery').values({id:randomUUID(),business_id:template.business_id,post_id:post.id,target_id:t.target_id,external_message_id:null,last_error:null}).execute();}const next=nextOccurrence(schedule.rule as Recurrence,new Date());await tx.updateTable('post_schedule').set({next_at:next,active:!!next}).where('post_id','=',schedule.post_id).execute();return true;});
}
