import { AppError } from '../http/errors.ts';
const instructions={generate:'Напиши публикацию по заданию.',rewrite:'Перепиши текст другими словами.',shorten:'Сократи текст.',expand:'Расширь текст без выдуманных фактов.',selling:'Сделай текст более продающим без недостоверных обещаний.',formal:'Сделай текст более официальным.',friendly:'Сделай текст дружелюбнее.',correct:'Исправь ошибки.',add_emoji:'Добавь уместные эмодзи.',remove_emoji:'Убери эмодзи.',variant:'Предложи другой вариант.'};
export async function generatePost(raw:Record<string,unknown>,options:{token?:string;model?:string;transport?:typeof fetch}={}){
 const action=String(raw.action??'generate') as keyof typeof instructions;const prompt=typeof raw.prompt==='string'?raw.prompt.trim():'';const text=typeof raw.text==='string'?raw.text.trim():'';
 if(!instructions[action]||prompt.length>4000||text.length>8000||!(prompt||text))throw new AppError(400,'INVALID_AI_INPUT','Опишите публикацию или введите текст.');
 if(/\b\d{6,}:\w{20,}|\bsk-[a-zA-Z0-9_-]{16,}|-----BEGIN .*PRIVATE KEY-----/.test(prompt+'\n'+text))throw new AppError(400,'AI_SECRET_REJECTED','Удалите секретные ключи из текста.');
 const token=options.token??process.env.AI_API_TOKEN,model=options.model??process.env.AI_MODEL;if(!token||!model)throw new AppError(503,'AI_NOT_CONFIGURED','Генерация текста пока не настроена.');
 const requestId=crypto.randomUUID(),started=Date.now();try{
  const response=await (options.transport??fetch)('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},redirect:'error',signal:AbortSignal.timeout(30000),body:JSON.stringify({model,store:false,max_output_tokens:2048,instructions:'Ты редактор публикаций для бизнеса. Верни только текст черновика до 4096 символов. Не публикуй и не выполняй внешних действий. '+instructions[action],input:[prompt,text].filter(Boolean).join('\n\n')})});
  const data=await response.json() as {status?:string;output?:{type?:string;content?:{type?:string;text?:string}[]}[]};if(!response.ok||data.status!=='completed')throw Error();const output=(data.output??[]).filter(x=>x.type==='message').flatMap(x=>x.content??[]).filter(x=>x.type==='output_text').map(x=>x.text??'').join('\n').trim();if(!output||output.length>4096)throw Error();console.info(JSON.stringify({code:'AI_DRAFT_CREATED',requestId,durationMs:Date.now()-started}));return {text:output,status:'draft' as const};
 }catch{console.error(JSON.stringify({code:'AI_GENERATION_FAILED',requestId,durationMs:Date.now()-started}));throw new AppError(503,'AI_UNAVAILABLE','Не удалось создать текст. Попробуйте ещё раз.');}
}
